select NAME+'('+SUBSTRING(OCCUPATION, 1, 1)+')' as OCC from OCCUPATIONS ORDER BY NAME;
SELECT 'There are a total of '+ CAST(COUNT(OCCUPATION) AS CHAR) +' '+LOWER(OCCUPATION)+'s.'
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION), OCCUPATION;